site_name: PokerFileSorter Documentation
theme: readthedocs
plugins:
  - search
  - mkdocstrings:
      default_handler: python

nav:
  - Home: index.md
  - API Reference:
    - main: main.md
    - file_sorter: file_sorter.md
    - config: config.md
      